{
  "uid" : "f5b01f96a6a580a2",
  "name" : "test_broken",
  "fullName" : "TK_GUI.gui_12#test_broken",
  "historyId" : "1375d96889065df121da8b9b6e3bd2b5",
  "time" : {
    "start" : 1607337674634,
    "stop" : 1607337674635,
    "duration" : 1
  },
  "status" : "broken",
  "statusMessage" : "Exception: oops",
  "statusTrace" : "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\nTK_GUI\\gui_12.py:28: Exception",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "TK_GUI"
  }, {
    "name" : "suite",
    "value" : "gui_12"
  }, {
    "name" : "host",
    "value" : "duang"
  }, {
    "name" : "thread",
    "value" : "12904-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "TK_GUI.gui_12"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "f5b01f96a6a580a2.json",
  "parameterValues" : [ ]
}