INFO     root:base.py:52 正在点击元素：('xpath', "//*[text()='信息管理']/.")
INFO     root:base.py:27 正在查找元素：('xpath', "//*[text()='信息管理']/.")
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0413EFD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/8c766647-5d29-474c-ab8c-1403d3ca2977/element
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04165C30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/8c766647-5d29-474c-ab8c-1403d3ca2977/element
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04165FB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/8c766647-5d29-474c-ab8c-1403d3ca2977/element